# Generated by Django 2.2.6 on 2019-10-12 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=50)),
                ('risk_factor', models.PositiveSmallIntegerField()),
                ('amount_from', models.PositiveIntegerField()),
                ('amount_to', models.PositiveIntegerField()),
            ],
        ),
    ]
