# Generated by Django 2.2.6 on 2019-10-12 23:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('money', models.PositiveIntegerField()),
                ('days', models.PositiveIntegerField()),
                ('investment_returned', models.FloatField()),
                ('return_percent', models.FloatField()),
                ('buy_coords', models.CharField(max_length=1500)),
                ('sell_coords', models.CharField(max_length=1500)),
                ('plot_coords', models.CharField(max_length=1500)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.Company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
