# Generated by Django 2.2.6 on 2019-10-13 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_botrun'),
    ]

    operations = [
        migrations.AddField(
            model_name='botrun',
            name='money_left',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
