# Generated by Django 2.2.6 on 2019-10-13 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_botrun_money_left'),
    ]

    operations = [
        migrations.AddField(
            model_name='botrun',
            name='redeemed',
            field=models.BooleanField(default=True),
        ),
    ]
