# Generated by Django 2.2.6 on 2019-10-13 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_botrun_redeemed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botrun',
            name='redeemed',
            field=models.BooleanField(default=False),
        ),
    ]
