# Generated by Django 2.2.6 on 2019-10-13 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0005_auto_20191013_0323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botrun',
            name='buy_coords',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='botrun',
            name='plot_coords',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='botrun',
            name='sell_coords',
            field=models.TextField(),
        ),
    ]
